# Generated by Django 5.2 on 2025-04-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_content_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('memory', models.PositiveIntegerField(help_text='GB')),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('used', 'Ishlatilgan'), ('refurbished', 'Ta’mirlangan')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
